project:
  type: website
  output-dir: docs
  render: 
    - cann_dashboard.qmd

website:
  title: "Canning Weir Pool Dashboard"
  page-navigation: false
  repo-url: https://github.com/flare-forecast/cann-dashboard
  repo-actions: [source, issue]

editor: visual
