project:
  type: website
  output-dir: docs
  render: 
    - cann_dashboard.qmd

website:
  title: "Canning Weir Pool Dashboard"
  page-navigation: true
  repo-url: https://github.com/flare-forecast/cann-dashboard
  repo-actions: [source, issue]
  sidebar:
    style: docked
    search: true
    background: primary
    foreground: primary
    border: true

editor: visual
brand: _brand.yaml